[General]
DisplayServer=wayland
RememberLastSession=false
ReuseSession=false
GreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=layer-shell,KWIN_DRM_DEVICES=/dev/dri/intel-igpu,KWIN_DRM_NO_AMS=1,KWIN_DRM_USE_MODIFIERS=0,KWIN_DRM_DISABLE_TRIPLE_BUFFERING=1

[Wayland]
CompositorCommand=env KWIN_DRM_DEVICES=/dev/dri/intel-igpu KWIN_DRM_NO_AMS=1 KWIN_DRM_USE_MODIFIERS=0 KWIN_DRM_DISABLE_TRIPLE_BUFFERING=1 /usr/bin/kwin_wayland --drm --no-lockscreen --no-global-shortcuts --locale1
